### ISSUE TITLE
set permissions for this repo

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/export_archivesspace_xml#3]
I don't think I have management permissions on this repo. 

Can we set something at the organization level so eddie/jonathan/chuck have management permissions on all repos, so we don't have to set them up individually?

Alternately, document in wiki how to set them up individually with a step-by-step.

**Comment by eddierubeiz** [comment]
Yup --  here's the recipe:
- https://github.com/sciencehistory/export_archivesspace_xml/settings/access
- Click "Add Team"
- Search for "@science_history/admin_access" and gave the group admin access.
- Remove yourself as an admin (since you're already part of the above group).

Also added the recipe here: https://chemheritage.atlassian.net/wiki/spaces/HDCSD/pages/2152267777/Github+administration+recipes
